  name = "2U X 2U Air Block"
  watts = 0.0
  material = "library/components/materials/air_block_shell_effective.toml"
  
  [size]
  units = "u"
  width = 10.0
  depth = 1.7
  height = 2.0
  
  [[internal_regions]]
  name = "Air"
  state = "air"
  [internal_regions.position]
  units = "u"
  x = 0.0
  y = 0.0
  z = 0.0
  [internal_regions.size]
  units = "u"
  width = 10.0
  depth = 1.7
  height = 2.0
  
  
  
  
  
  
  
  
