  name = "Tripp Lite B020-U08-19-IP KVM"
  watts = 6.0 # in walls
  material = "library/components/materials/mixed_electronics.toml"
  
  [size]
  units = "mm"
  width = 480.0
  depth = 685.0
  height = 44.0
  
  
  
  
  
  
  
  
