# 44.45 mm/432.5 mm/585.6 mm 

# components/server_1u.toml

name = "Keysight N6701 PS"
watts = 100.0

[size]
units = "mm"
width = 425.0
depth = 549.7
height = 44.45

# weight = 26 lb / 0.011 m^3 - 1069.8250 kg/m^3
[material] # alum enclosure
rho = 2700
cp = 900.0
k = 150.0


# ----- region 1 --------

[[internal_regions]]
name = "air_region"
state = "air"

[internal_regions.position] # shell
units = "mm"
x = 5.0
y = 5.0
z = 5.0

[internal_regions.size]
units = "mm"
width = 415.0
depth = 539.7
height = 34.45


# ----- region 2 --------

[[internal_regions]]
name = "Power block"
state = "solid"
watts = 120.0

[internal_regions.position]
units = "mm"
x = 12.5
y = 5
z = 5

[internal_regions.size]
units = "mm"
width = 400.0
depth = 250.0
height = 20.0

[internal_regions.material]
rho = 2330.0
cp = 700.0
k = 130.0

# ----- region 3 --------

[[internal_regions]]
name = "front intake"
state = "vent"
shape = "rectangular"
free_area_ratio = 0.5
vent_discharge_coeff = 0.85

[internal_regions.position]
units = "mm"
x = 425.0
y = 125.0
z = 11.1125

[internal_regions.size]
units = "mm"
width = 0.0
depth = 150.0
height = 22.225


[internal_regions.normal]
x = 0.0
y = 1.0
z = 0.0

# ----- region 4 --------

[[internal_regions]]
state = "fan"
name = "Internal Exhaust Fan"
shape = "rectangular"
flow_type = "exhaust"
cfm = 35.0

[internal_regions.size]
units = "mm"
width = 0.0
depth = 150.0
height = 22.225

[internal_regions.position]
units = "mm"
x = 0.0
y = 125.0
z = 11.1125

[internal_regions.direction]
x = 0.0
y = -1.0
z = 0.0

# ----- region 5 --------

[[internal_regions]]
name = "back block"
state = "solid"
watts = 120.0

[internal_regions.position]
units = "mm"
x = 10.0
y = 260
z = 5

[internal_regions.size]
units = "mm"
width = 140.0
depth = 270.0
height = 20.0

[internal_regions.material]
rho = 2330.0
cp = 700.0
k = 130.0

# ----- region 6 --------

[[internal_regions]]
name = "input blocks"
state = "solid"
watts = 120.0

[internal_regions.position]
units = "mm"
x = 150.0
y = 260
z = 5

[internal_regions.size]
units = "mm"
width = 260.0
depth = 270.0
height = 20.0

[internal_regions.material]
rho = 2330.0
cp = 700.0
k = 130.0

# ----- region 7 --------

[[internal_regions]]
state = "fan"
name = "back exhaust fan"
shape = "rectangular"
flow_type = "exhaust"
cfm = 35.0

[internal_regions.size]
units = "mm"
width = 270.0
depth = 0.0
height = 22.225

[internal_regions.position]
units = "mm"
x = 130.0
y = 549.7
z = 11.1125

[internal_regions.direction]
x = -1.0
y = 0.0
z = 0.0

# ----- region 8 --------

[[internal_regions]]
name = "back intake"
state = "vent"
shape = "rectangular"
free_area_ratio = 0.5
vent_discharge_coeff = 0.85

[internal_regions.position]
units = "mm"
x = 0.0
y = 350.0
z = 11.1125

[internal_regions.size]
units = "mm"
width = 0.0
depth = 150.0
height = 22.225

[internal_regions.normal]
x = 0.0
y = 1.0
z = 0.0
