# 44.45 mm/432.5 mm/585.6 mm 

# components/server_1u.toml

name = "Keysight N6701 PS"
watts = 100.0

[size]
units = "mm"
width = 400.0
depth = 400.0
height = 44.45

# weight = 26 lb / 0.011 m^3 - 1069.8250 kg/m^3
[material] # alum enclosure
rho = 2700
cp = 900.0
k = 150.0


# ----- region 1 --------

[[internal_regions]]
name = "air_region"
state = "air"

[internal_regions.position] # shell
units = "mm"
x = 10.0
y = 10.0
z = 10.0

[internal_regions.size]
units = "mm"
width = 350.0
depth = 350.0
height = 30.0


# # ----- region 2 --------

# [[internal_regions]]
# name = "Power block"
# state = "solid"
# watts = 120.0

# [internal_regions.position]
# units = "mm"
# x = 5
# y = 5
# z = 5

# [internal_regions.size]
# units = "mm"
# width = 380.0
# depth = 250.0
# height = 28.0

# [internal_regions.material]
# rho = 2330.0
# cp = 700.0
# k = 130.0
