# components/server_1u.toml

name = "Generic 1U Server"
type = "server"

[size]
width = 0.4826
depth = 0.700
height = 0.04445

[material]
density = 2700.0
specific_heat = 900.0
conductivity = 15.0

heat_generation = 500.0

[[internal_regions]]
name = "CPU"
region_type = "solid"

[internal_regions.local_position]
x = 0.18
y = 0.25
z = 0.012

[internal_regions.size]
width = 0.06
depth = 0.06
height = 0.015

[internal_regions.material]
density = 2330.0
specific_heat = 700.0
conductivity = 130.0

internal_regions.heat_generation = 160.0

[[internal_regions]]
name = "Power Supply"
region_type = "solid"

[internal_regions.local_position]
x = 0.36
y = 0.48
z = 0.005

[internal_regions.size]
width = 0.10
depth = 0.18
height = 0.032

internal_regions.heat_generation = 120.0