# models/rack_fire_case.toml

[rack]
width = 0.60
depth = 1.00
height = 1.80

[[component_instances]]
name = "Server-A"
definition = "../components/server_1u.toml"

[component_instances.position]
x = 0.05
y = 0.10
z = 0.30

[[component_instances]]
name = "Server-B"
definition = "../components/server_1u.toml"

[component_instances.position]
x = 0.05
y = 0.10
z = 0.34445