name = "Rack Test"

# -------------------------------------------------------------
# Simulation
# -------------------------------------------------------------

[simulation]
dt = 0.05
duration = 10.0
output_interval = 25
max_timesteps = 1000000
max_updates = 10000000
max_cell_count = 10000000
max_megabyte_usage = 40
update_flow_interval = 10

# -------------------------------------------------------------
# Flow Solver
# -------------------------------------------------------------

[flow_solver]
enable_flow_solver = true
resistivity = 4.6
tolerance = 1e-6
max_iterations = 2000
sor_omega = 1.1
max_outer_iters = 20
flow_tolerance = 1e-3

# -------------------------------------------------------------
# Environment - air properties
# -------------------------------------------------------------

[environment]
humidity = 30.0
elevation = 5500.0
T_ambient = 20.0
cp = 1005.5
k = 0.02587
mu = 1.81e-5
pr = 0.71
rho = 1.225

# -------------------------------------------------------------
# Mesh
# -------------------------------------------------------------

[mesh]
dx = 0.1
dy = 0.1
dz = 0.01

# -------------------------------------------------------------
# Rack
# -------------------------------------------------------------

[rack] 
name = "testing rack"

[rack.size]
units = "u"
width = 10.0
depth = 10.0
height = 10.0

[rack.ambient]
temperature = 293.15
pressure = 101325
density = 1.204
cp = 1005
k = 0.02587
rho = 1.204

# -------------------------------------------------------------
# Components
# -------------------------------------------------------------

[[components]]
name = "Server 1"
watts = 600

[components.position]
units = "u"
x = 0.0
y = 0.0
z = 2.0

[components.size]
units = "u"
width = 5.0
depth = 5.0
height = 1.0

[components.material]
rho = 2700
cp = 900
k = 150

# ----- region 1 --------

[[components.internal_regions]]
name = "CPU"
watts = 200
state = "solid" 

[components.internal_regions.position] 
# relative to bot left corner parent component
units = "u"
x = 0.0
y = 0.0
z = 0.0

[components.internal_regions.size]
units = "u"
width = 1.0
depth = 5.0
height = 1.0

[components.internal_regions.material]
rho = 2300
cp = 700
k = 120



[[components]]
template = "library/components/server1.toml"

[components.position]
units = "u"
x = 0
y = 0
z = 4

[[components]]
template = "library/components/keysight_N6701C.toml"

[components.position]
units = "u"
x = 0
y = 0
z = 0
# -------------------------------------------------------------
# Fans
# -------------------------------------------------------------

[[fans]]
name = "Top fan"
shape = "circular"
diameter = 0.1
diameter_units = "m"
cfm = 80.0
flow_type = "exhaust"
curve = "delta_afb0812_12v"

[fans.position]
units = "u"
x = 2.5
y = 2.5
z = 10.0

[fans.direction]
x = 0.0
y = 0.0
z = 1.0


# -------------------------------------------------------------
# Vents
# -------------------------------------------------------------

# [[vents]]
# name = "main front vent"
# shape = "rectangular"
# free_area_ratio = 0.5

# [vents.position]
# units = "u"
# x = 2.5
# y = 0
# z = 4

# [vents.size]
# units = "u"
# width = 2
# depth = 0
# height = 1

# [vents.normal]
# x = 0.0
# y = 1.0
# z = 0.0

# [[vents]]
# name = "main front vent"
# shape = "circular"
# diameter = 0.1
# diameter_units = "m"
# free_area_ratio = 0.5
# vent_discharge_coeff = 0.5

# [vents.position]
# units = "u"
# x = 2.5
# y = 0
# z = 4

# [vents.normal]
# x = 0.0
# y = 1.0
# z = 0.0
