#!/usr/bin/env python3
"""Characterize and generate a generic air-cooled rack-server component.

The inferred heat load is the heat measured in the device airflow:

    Q_air = mass_flow * cp_air * (T_exhaust - T_intake)

Temperatures may be supplied in K or C because only their difference is used.
This is a rack-level boundary model, not an electronics-hotspot model.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


U_HEIGHT_MM = 44.45


def positive(value: str) -> float:
    number = float(value)
    if not math.isfinite(number) or number <= 0.0:
        raise argparse.ArgumentTypeError("must be a finite value greater than zero")
    return number


def finite(value: str) -> float:
    number = float(value)
    if not math.isfinite(number):
        raise argparse.ArgumentTypeError("must be finite")
    return number


def slug(text: str) -> str:
    cleaned = "".join(c.lower() if c.isalnum() else "_" for c in text)
    return "_".join(part for part in cleaned.split("_") if part) or "generic_server"


def component_toml(name: str, rack_units: int, width: float, depth: float,
                   watts: float, mass_flow: float, curve_name: str,
                   heat_placement: str = "solid") -> str:
    if heat_placement not in ("solid", "air"):
        raise ValueError("heat_placement must be 'solid' or 'air'")
    height = rack_units * U_HEIGHT_MM
    margin = min(5.0, 0.08 * height)
    air_w = width - 2.0 * margin
    air_d = depth
    air_h = height - 2.0 * margin
    if min(air_w, air_d, air_h) <= 0.0:
        raise ValueError("component dimensions are too small for an internal air region")

    block_w = 0.70 * air_w
    block_d = 0.50 * air_d
    block_h = 0.40 * air_h
    block_x = (width - block_w) / 2.0
    block_y = margin + 0.25 * air_d
    block_z = (height - block_h) / 2.0
    opening_w = 0.85 * air_w
    opening_h = 0.75 * air_h
    # The fan spans the tunnel section so there is no zero-resistance bypass
    # path around the equivalent device fan.
    fan_w = opening_w
    fan_h = opening_h
    tunnel_x = (width - opening_w) / 2.0
    tunnel_z = (height - opening_h) / 2.0
    fan_y = 0.90 * depth
    cfm = mass_flow / 1.2041 * 2118.880003
    qvol = watts / ((block_w * block_d * block_h) * 1.0e-9)
    air_watts = watts if heat_placement == "air" else 0.0
    solid_watts = watts if heat_placement == "solid" else 0.0

    return f'''# Generated by tools/generic_server_characterizer.py
# Rack-level boundary model. No internal temperature is a chip temperature.
# Target measured mass flow: {mass_flow:.9g} kg/s ({cfm:.6g} CFM at 1.2041 kg/m^3)
# The front-to-rear air tunnel reaches both chassis faces. Flow devices are
# inset inside the tunnel so they always have fluid cells upstream/downstream.
# Inferred air-side heat: {watts:.9g} W
# Heat placement: {heat_placement}
# Nominal solid-block volumetric heat generation (when selected): {qvol:.9g} W/m^3

name = {json.dumps(name)}
watts = 0.0

[size]
units = "mm"
width = {width:.9g}
depth = {depth:.9g}
height = {height:.9g}

[material]
# Effective chassis properties; calibrate only when surface-temperature data exist.
rho = 1200.0
cp = 800.0
k = 10.0

[[internal_regions]]
name = "Interior air"
state = "air"
watts = {air_watts:.9g}

[internal_regions.position]
units = "mm"
x = {tunnel_x:.9g}
y = 0.0
z = {tunnel_z:.9g}

[internal_regions.size]
units = "mm"
width = {opening_w:.9g}
depth = {air_d:.9g}
height = {opening_h:.9g}

[[internal_regions]]
name = "Equivalent heat block"
state = "solid"
watts = {solid_watts:.9g}

[internal_regions.position]
units = "mm"
x = {block_x:.9g}
y = {block_y:.9g}
z = {block_z:.9g}

[internal_regions.size]
units = "mm"
width = {block_w:.9g}
depth = {block_d:.9g}
height = {block_h:.9g}

[internal_regions.material]
# Effective mixed electronics material, not literal aluminum or silicon.
rho = 1200.0
cp = 800.0
k = 10.0

[[internal_regions]]
name = "Front intake"
state = "vent"
shape = "rectangular"
free_area_ratio = 0.55
vent_discharge_coeff = 0.82

[internal_regions.position]
units = "mm"
x = {width / 2.0:.9g}
y = {margin:.9g}
z = {height / 2.0:.9g}

[internal_regions.size]
units = "mm"
width = {opening_w:.9g}
depth = 0.0
height = {opening_h:.9g}

[internal_regions.normal]
x = 0.0
y = 1.0
z = 0.0

[[internal_regions]]
name = "Rear exhaust fan"
state = "fan"
shape = "rectangular"
flow_type = "exhaust"
cfm = {cfm:.9g}
curve = {json.dumps(curve_name)}

[internal_regions.position]
units = "mm"
x = {width / 2.0:.9g}
y = {fan_y:.9g}
z = {height / 2.0:.9g}

[internal_regions.size]
units = "mm"
width = {fan_w:.9g}
depth = 0.0
height = {fan_h:.9g}

[internal_regions.direction]
x = 0.0
y = 1.0
z = 0.0
'''


def fitted_fan_curve(mass_flow: float, rho: float, pressure: float,
                     free_flow_multiplier: float) -> dict[str, float]:
    """Fit P(Q)=a-cQ^2 through the measured point and zero-pressure flow."""
    q_operating = mass_flow / rho
    q_free = free_flow_multiplier * q_operating
    denominator = 1.0 - (q_operating / q_free) ** 2
    a = pressure / denominator
    c = a / (q_free * q_free)
    return {
        "a": a,
        "b": 0.0,
        "c": c,
        "rho_rated": rho,
        "operating_flow_m3_s": q_operating,
        "free_flow_m3_s": q_free,
        "operating_pressure_pa": pressure,
    }


def fan_curve_toml(name: str, curve: dict[str, float]) -> str:
    return f'''# Equivalent curve fitted by generic_server_characterizer.py.
# Valid near the measured operating point; not a manufacturer fan curve.
[[fan_curve]]
name = {json.dumps(name)}
a = {curve["a"]:.17g}
b = {curve["b"]:.17g}
c = {curve["c"]:.17g}
rho_rated = {curve["rho_rated"]:.17g}
'''


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Infer air-side component watts and optionally write a generic server TOML.")
    parser.add_argument("--name", default="Generic server")
    parser.add_argument("--rack-units", type=int, choices=(1, 2, 3), required=True)
    parser.add_argument("--width-mm", type=positive, default=482.0)
    parser.add_argument("--depth-mm", type=positive, required=True)
    parser.add_argument("--mass-flow-kg-s", type=positive, required=True)
    parser.add_argument("--intake-temp", type=finite, required=True,
                        help="mass-weighted intake temperature in K or C")
    parser.add_argument("--exhaust-temp", type=finite, required=True,
                        help="mass-weighted exhaust temperature in the same unit")
    parser.add_argument("--cp-air", type=positive, default=1005.5)
    parser.add_argument("--air-density-kg-m3", type=positive, default=1.2041)
    parser.add_argument("--fan-pressure-rise-pa", type=positive,
                        help="measured static pressure rise at the supplied mass flow")
    parser.add_argument("--fan-free-flow-multiplier", type=positive, default=1.25,
                        help="assumed zero-pressure flow divided by measured flow (default: 1.25)")
    parser.add_argument("--fan-curve-name",
                        help="generated curve name; defaults to <device-name>_equivalent")
    parser.add_argument("--fan-curve-output", type=Path,
                        help="write a fan-curve TOML snippet when pressure rise is supplied")
    parser.add_argument("--input-watts", "--electrical-watts", dest="input_watts",
                        type=positive,
                        help="measured electrical input power; electrical-watts is an alias")
    parser.add_argument("--efficiency-percent", type=positive,
                        help="power-conversion efficiency in percent (greater than 0 and at most 100)")
    parser.add_argument(
        "--heat-load-source", choices=("airflow", "input", "conversion-loss"),
        default="airflow",
        help="source used for generated block watts (default: airflow)")
    parser.add_argument(
        "--heat-placement", choices=("solid", "air"), default="solid",
        help="place selected watts in the solid block or interior air (default: solid)")
    parser.add_argument("--output", type=Path,
                        help="write a customized component TOML to this path")
    parser.add_argument("--json-output", type=Path,
                        help="write the calculated characterization as JSON")
    parser.add_argument("--model-source", type=Path,
                        help="existing model TOML to copy with component replacements")
    parser.add_argument("--model-output", type=Path,
                        help="destination for the derived model TOML")
    parser.add_argument("--replace-component", action="append", default=[],
                        metavar="OLD=NEW",
                        help="component template path replacement; may be repeated")
    args = parser.parse_args()

    delta_t = args.exhaust_temp - args.intake_temp
    if delta_t <= 0.0:
        parser.error("exhaust-temp must be greater than intake-temp")
    airside_watts = args.mass_flow_kg_s * args.cp_air * delta_t
    if args.efficiency_percent is not None and args.efficiency_percent > 100.0:
        parser.error("efficiency-percent must not exceed 100")
    if args.heat_load_source in ("input", "conversion-loss") and args.input_watts is None:
        parser.error(f"heat-load-source={args.heat_load_source} requires input-watts")
    if args.heat_load_source == "conversion-loss" and args.efficiency_percent is None:
        parser.error("heat-load-source=conversion-loss requires efficiency-percent")
    efficiency = (args.efficiency_percent / 100.0
                  if args.efficiency_percent is not None else None)
    conversion_loss_watts = (
        args.input_watts * (1.0 - efficiency)
        if args.input_watts is not None and efficiency is not None else None)
    if args.heat_load_source == "input":
        watts = args.input_watts
    elif args.heat_load_source == "conversion-loss":
        watts = conversion_loss_watts
    else:
        watts = airside_watts
    if args.fan_free_flow_multiplier <= 1.0:
        parser.error("fan-free-flow-multiplier must be greater than 1")
    curve_name = args.fan_curve_name or f"{slug(args.name)}_equivalent"
    curve = None
    if args.fan_pressure_rise_pa is not None:
        curve = fitted_fan_curve(
            args.mass_flow_kg_s, args.air_density_kg_m3,
            args.fan_pressure_rise_pa, args.fan_free_flow_multiplier)
    elif args.fan_curve_output is not None:
        parser.error("fan-curve-output requires fan-pressure-rise-pa")
    volume = (0.70 * (args.width_mm - 10.0)) * (0.50 * (args.depth_mm - 10.0)) * \
             (0.40 * (args.rack_units * U_HEIGHT_MM - 10.0)) * 1.0e-9
    report = {
        "name": args.name,
        "rack_units": args.rack_units,
        "width_mm": args.width_mm,
        "depth_mm": args.depth_mm,
        "height_mm": args.rack_units * U_HEIGHT_MM,
        "mass_flow_kg_s": args.mass_flow_kg_s,
        "intake_temperature": args.intake_temp,
        "exhaust_temperature": args.exhaust_temp,
        "temperature_rise_k": delta_t,
        "cp_air_j_kg_k": args.cp_air,
        "inferred_airside_watts": airside_watts,
        "selected_heat_load_source": args.heat_load_source,
        "generated_heat_block_watts": watts,
        "heat_placement": args.heat_placement,
        "nominal_heat_block_qvol_w_m3": watts / volume,
        "template": f"library/components/generic_server_{args.rack_units}u.toml",
        "fan_curve_name": curve_name if curve else "generic_80mm_low_speed",
        "fan_curve_status": "operating-point fit" if curve else "provisional",
    }
    if curve:
        report["fan_curve"] = curve
    if args.input_watts is not None:
        report["input_watts"] = args.input_watts
        report["airside_heat_fraction_of_input"] = airside_watts / args.input_watts
        report["input_minus_airside_watts"] = args.input_watts - airside_watts
    if efficiency is not None:
        report["efficiency_fraction"] = efficiency
        if args.input_watts is not None:
            report["useful_output_watts"] = args.input_watts * efficiency
            report["conversion_loss_watts"] = conversion_loss_watts

    print(f"Temperature rise:       {delta_t:.6g} K")
    print(f"Mass flow:              {args.mass_flow_kg_s:.6g} kg/s")
    print(f"Air-side heat:          {airside_watts:.6g} W")
    print(f"Heat-load source:       {args.heat_load_source}")
    print(f"Heat-block watts:       {watts:.6g} W")
    print(f"Heat placement:         {args.heat_placement}")
    print(f"Matching base template: generic_server_{args.rack_units}u.toml")
    if curve:
        print(f"Fan curve:              {curve_name}")
        print(f"  a:                    {curve['a']:.9g} Pa")
        print(f"  b:                    {curve['b']:.9g} Pa/(m^3/s)")
        print(f"  c:                    {curve['c']:.9g} Pa/(m^3/s)^2")
    else:
        print("Fan curve:              generic_80mm_low_speed (provisional)")
    if args.input_watts is not None:
        fraction = airside_watts / args.input_watts
        print(f"Electrical input:       {args.input_watts:.6g} W")
        print(f"Air-side heat fraction: {100.0 * fraction:.3f}%")
        if not 0.8 <= fraction <= 1.1:
            print("WARNING: airflow heat and electrical load differ by more than 20%.")
    if efficiency is not None and args.input_watts is not None:
        print(f"Conversion efficiency: {100.0 * efficiency:.3f}%")
        print(f"Conversion loss:        {conversion_loss_watts:.6g} W")
        if args.heat_load_source == "input":
            print("NOTE: For a server, useful PSU output also becomes heat inside the device;")
            print("      total input watts are therefore normally the correct heat load.")

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(component_toml(
            args.name, args.rack_units, args.width_mm, args.depth_mm,
            watts, args.mass_flow_kg_s,
            curve_name if curve else "generic_80mm_low_speed",
            args.heat_placement), encoding="utf-8")
        print(f"Wrote component:        {args.output}")
    if args.fan_curve_output and curve:
        args.fan_curve_output.parent.mkdir(parents=True, exist_ok=True)
        args.fan_curve_output.write_text(
            fan_curve_toml(curve_name, curve), encoding="utf-8")
        print(f"Wrote fan curve:        {args.fan_curve_output}")
    if args.json_output:
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote report:           {args.json_output}")
    if (args.model_source is None) != (args.model_output is None):
        parser.error("model-source and model-output must be supplied together")
    if args.model_source:
        model_text = args.model_source.read_text(encoding="utf-8")
        for replacement in args.replace_component:
            if "=" not in replacement:
                parser.error("replace-component must use OLD=NEW")
            old, new = replacement.split("=", 1)
            if old not in model_text:
                parser.error(f"component path not found in model-source: {old}")
            model_text = model_text.replace(old, new)
        model_text = (
            "# Generic-component comparison model generated from "
            f"{args.model_source.as_posix()}\n"
            "# Detailed component model remains unchanged.\n" + model_text)
        args.model_output.parent.mkdir(parents=True, exist_ok=True)
        args.model_output.write_text(model_text, encoding="utf-8")
        print(f"Wrote derived model:    {args.model_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
