#!/usr/bin/env python3
"""Characterize and generate a generic air-cooled rack-server component.

The inferred heat load is the heat measured in the device airflow:

    Q_air = mass_flow * cp_air * (T_exhaust - T_intake)

Temperatures may be supplied in K or C because only their difference is used.
This is a rack-level boundary model, not an electronics-hotspot model.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


U_HEIGHT_MM = 44.45


def positive(value: str) -> float:
    number = float(value)
    if not math.isfinite(number) or number <= 0.0:
        raise argparse.ArgumentTypeError("must be a finite value greater than zero")
    return number


def finite(value: str) -> float:
    number = float(value)
    if not math.isfinite(number):
        raise argparse.ArgumentTypeError("must be finite")
    return number


def slug(text: str) -> str:
    cleaned = "".join(c.lower() if c.isalnum() else "_" for c in text)
    return "_".join(part for part in cleaned.split("_") if part) or "generic_server"


def component_toml(name: str, rack_units: int, width: float, depth: float,
                   watts: float, mass_flow: float) -> str:
    height = rack_units * U_HEIGHT_MM
    margin = min(5.0, 0.08 * height)
    air_w = width - 2.0 * margin
    air_d = depth - 2.0 * margin
    air_h = height - 2.0 * margin
    if min(air_w, air_d, air_h) <= 0.0:
        raise ValueError("component dimensions are too small for an internal air region")

    block_w = 0.70 * air_w
    block_d = 0.50 * air_d
    block_h = 0.40 * air_h
    block_x = (width - block_w) / 2.0
    block_y = margin + 0.25 * air_d
    block_z = (height - block_h) / 2.0
    opening_w = 0.85 * air_w
    opening_h = 0.75 * air_h
    cfm = mass_flow / 1.2041 * 2118.880003
    qvol = watts / ((block_w * block_d * block_h) * 1.0e-9)

    return f'''# Generated by tools/generic_server_characterizer.py
# Rack-level boundary model. The solid-block temperature is not a chip temperature.
# Target measured mass flow: {mass_flow:.9g} kg/s ({cfm:.6g} CFM at 1.2041 kg/m^3)
# Inferred air-side heat: {watts:.9g} W
# Nominal block volumetric heat generation: {qvol:.9g} W/m^3

name = {json.dumps(name)}
watts = 0.0

[size]
units = "mm"
width = {width:.9g}
depth = {depth:.9g}
height = {height:.9g}

[material]
# Effective chassis properties; calibrate only when surface-temperature data exist.
rho = 1200.0
cp = 800.0
k = 10.0

[[internal_regions]]
name = "Interior air"
state = "air"

[internal_regions.position]
units = "mm"
x = {margin:.9g}
y = {margin:.9g}
z = {margin:.9g}

[internal_regions.size]
units = "mm"
width = {air_w:.9g}
depth = {air_d:.9g}
height = {air_h:.9g}

[[internal_regions]]
name = "Equivalent heat block"
state = "solid"
watts = {watts:.9g}

[internal_regions.position]
units = "mm"
x = {block_x:.9g}
y = {block_y:.9g}
z = {block_z:.9g}

[internal_regions.size]
units = "mm"
width = {block_w:.9g}
depth = {block_d:.9g}
height = {block_h:.9g}

[internal_regions.material]
# Effective mixed electronics material, not literal aluminum or silicon.
rho = 1200.0
cp = 800.0
k = 10.0

[[internal_regions]]
name = "Front intake"
state = "vent"
shape = "rectangular"
free_area_ratio = 0.55
vent_discharge_coeff = 0.82

[internal_regions.position]
units = "mm"
x = {width / 2.0:.9g}
y = 0.0
z = {height / 2.0:.9g}

[internal_regions.size]
units = "mm"
width = {opening_w:.9g}
depth = 0.0
height = {opening_h:.9g}

[internal_regions.normal]
x = 0.0
y = 1.0
z = 0.0

[[internal_regions]]
name = "Rear exhaust fan"
state = "fan"
shape = "rectangular"
flow_type = "exhaust"
cfm = {cfm:.9g}
curve = "generic_80mm_low_speed" # provisional; calibrate to measured mass flow

[internal_regions.position]
units = "mm"
x = {width / 2.0:.9g}
y = {depth:.9g}
z = {height / 2.0:.9g}

[internal_regions.size]
units = "mm"
width = {opening_w:.9g}
depth = 0.0
height = {opening_h:.9g}

[internal_regions.direction]
x = 0.0
y = 1.0
z = 0.0
'''


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Infer air-side component watts and optionally write a generic server TOML.")
    parser.add_argument("--name", default="Generic server")
    parser.add_argument("--rack-units", type=int, choices=(1, 2, 3), required=True)
    parser.add_argument("--width-mm", type=positive, default=482.0)
    parser.add_argument("--depth-mm", type=positive, required=True)
    parser.add_argument("--mass-flow-kg-s", type=positive, required=True)
    parser.add_argument("--intake-temp", type=finite, required=True,
                        help="mass-weighted intake temperature in K or C")
    parser.add_argument("--exhaust-temp", type=finite, required=True,
                        help="mass-weighted exhaust temperature in the same unit")
    parser.add_argument("--cp-air", type=positive, default=1005.5)
    parser.add_argument("--electrical-watts", type=positive,
                        help="optional measured electrical dissipation for an energy check")
    parser.add_argument("--output", type=Path,
                        help="write a customized component TOML to this path")
    parser.add_argument("--json-output", type=Path,
                        help="write the calculated characterization as JSON")
    args = parser.parse_args()

    delta_t = args.exhaust_temp - args.intake_temp
    if delta_t <= 0.0:
        parser.error("exhaust-temp must be greater than intake-temp")
    watts = args.mass_flow_kg_s * args.cp_air * delta_t
    volume = (0.70 * (args.width_mm - 10.0)) * (0.50 * (args.depth_mm - 10.0)) * \
             (0.40 * (args.rack_units * U_HEIGHT_MM - 10.0)) * 1.0e-9
    report = {
        "name": args.name,
        "rack_units": args.rack_units,
        "width_mm": args.width_mm,
        "depth_mm": args.depth_mm,
        "height_mm": args.rack_units * U_HEIGHT_MM,
        "mass_flow_kg_s": args.mass_flow_kg_s,
        "intake_temperature": args.intake_temp,
        "exhaust_temperature": args.exhaust_temp,
        "temperature_rise_k": delta_t,
        "cp_air_j_kg_k": args.cp_air,
        "inferred_airside_watts": watts,
        "nominal_heat_block_qvol_w_m3": watts / volume,
        "template": f"library/components/generic_server_{args.rack_units}u.toml",
    }
    if args.electrical_watts is not None:
        report["electrical_watts"] = args.electrical_watts
        report["airside_heat_fraction"] = watts / args.electrical_watts
        report["unaccounted_watts"] = args.electrical_watts - watts

    print(f"Temperature rise:       {delta_t:.6g} K")
    print(f"Mass flow:              {args.mass_flow_kg_s:.6g} kg/s")
    print(f"Heat-block watts:       {watts:.6g} W")
    print(f"Matching base template: generic_server_{args.rack_units}u.toml")
    if args.electrical_watts is not None:
        fraction = watts / args.electrical_watts
        print(f"Air-side heat fraction: {100.0 * fraction:.3f}%")
        if not 0.8 <= fraction <= 1.1:
            print("WARNING: airflow heat and electrical load differ by more than 20%.")

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(component_toml(
            args.name, args.rack_units, args.width_mm, args.depth_mm,
            watts, args.mass_flow_kg_s), encoding="utf-8")
        print(f"Wrote component:        {args.output}")
    if args.json_output:
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote report:           {args.json_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
